# Generated by Django 5.2.7 on 2025-12-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
