# Generated by Django 5.2.7 on 2025-12-10 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '簡単'), ('normal', '普通'), ('hard', '難しい')], max_length=10)),
                ('status', models.CharField(choices=[('completed', 'クリア'), ('abandoned', '途中終了')], max_length=20)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('matched_cards', models.IntegerField(default=0)),
                ('total_cards', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'difficulty'], name='app_gamerec_user_id_cca67a_idx'), models.Index(fields=['difficulty', 'time_taken'], name='app_gamerec_difficu_ca4513_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '簡単'), ('normal', '普通'), ('hard', '難しい')], max_length=10)),
                ('time_taken', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['difficulty', 'time_taken'],
                'indexes': [models.Index(fields=['difficulty', 'time_taken'], name='app_ranking_difficu_4a30d2_idx')],
                'unique_together': {('user', 'difficulty')},
            },
        ),
    ]
